[package]
name = "bevy_ui_extended"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
smallvec = "1.11.1"
bevy_rapier3d = "0.22.0"